[package]
name = "erno"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
num-traits = "0.2"
num-derive = "0.2"
itertools = "0.10"